# Generated by Django 3.2.16 on 2022-11-18 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_cpver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Cpver',
            new_name='Cover',
        ),
    ]
